# Generated by Django 5.0 on 2024-11-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveManagementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavemanagementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LeaveManagementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffproductivityaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StaffProductivityAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffproductivityaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StaffProductivityAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffturnoveraudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StaffTurnoverAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffturnoveraudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StaffTurnoverAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdevelopmentaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TrainingDevelopmentAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdevelopmentaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TrainingDevelopmentAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
