# Generated by Django 5.0 on 2024-11-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskand_compliance_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ComplianceAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ComplianceAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudmonitoringaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FraudMonitoringAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudmonitoringaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FraudMonitoringAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessmentaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RiskAssessmentAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessmentaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RiskAssessmentAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
