# Generated by Django 5.0 on 2024-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccuracyAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('errors_detected', models.PositiveIntegerField()),
                ('corrected_entries_percentage', models.FloatField()),
                ('audit_frequency', models.CharField(max_length=50)),
                ('system_generated_errors', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('manual_input_errors', models.PositiveIntegerField()),
                ('critical_errors', models.PositiveIntegerField()),
                ('accuracy_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAccuracyHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('errors_detected', models.PositiveIntegerField()),
                ('corrected_entries_percentage', models.FloatField()),
                ('audit_frequency', models.CharField(max_length=50)),
                ('system_generated_errors', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('manual_input_errors', models.PositiveIntegerField()),
                ('critical_errors', models.PositiveIntegerField()),
                ('accuracy_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAccuracyLive',
            fields=[
                ('errors_detected', models.PositiveIntegerField()),
                ('corrected_entries_percentage', models.FloatField()),
                ('audit_frequency', models.CharField(max_length=50)),
                ('system_generated_errors', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('manual_input_errors', models.PositiveIntegerField()),
                ('critical_errors', models.PositiveIntegerField()),
                ('accuracy_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAccuracyTemp',
            fields=[
                ('errors_detected', models.PositiveIntegerField()),
                ('corrected_entries_percentage', models.FloatField()),
                ('audit_frequency', models.CharField(max_length=50)),
                ('system_generated_errors', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('manual_input_errors', models.PositiveIntegerField()),
                ('critical_errors', models.PositiveIntegerField()),
                ('accuracy_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITTicketResolutionAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('tickets_raised', models.PositiveIntegerField()),
                ('tickets_resolved', models.PositiveIntegerField()),
                ('average_resolution_time_hours', models.FloatField()),
                ('high_priority_tickets', models.PositiveIntegerField()),
                ('unresolved_tickets', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('escalation_rate', models.FloatField()),
                ('resolution_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITTicketResolutionHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('tickets_raised', models.PositiveIntegerField()),
                ('tickets_resolved', models.PositiveIntegerField()),
                ('average_resolution_time_hours', models.FloatField()),
                ('high_priority_tickets', models.PositiveIntegerField()),
                ('unresolved_tickets', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('escalation_rate', models.FloatField()),
                ('resolution_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITTicketResolutionLive',
            fields=[
                ('tickets_raised', models.PositiveIntegerField()),
                ('tickets_resolved', models.PositiveIntegerField()),
                ('average_resolution_time_hours', models.FloatField()),
                ('high_priority_tickets', models.PositiveIntegerField()),
                ('unresolved_tickets', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('escalation_rate', models.FloatField()),
                ('resolution_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITTicketResolutionTemp',
            fields=[
                ('tickets_raised', models.PositiveIntegerField()),
                ('tickets_resolved', models.PositiveIntegerField()),
                ('average_resolution_time_hours', models.FloatField()),
                ('high_priority_tickets', models.PositiveIntegerField()),
                ('unresolved_tickets', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('escalation_rate', models.FloatField()),
                ('resolution_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUptimeAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('total_downtime_hours', models.FloatField()),
                ('uptime_percentage', models.FloatField()),
                ('scheduled_maintenance_hours', models.FloatField()),
                ('unscheduled_outage_hours', models.FloatField()),
                ('critical_systems_affected', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('system_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUptimeHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('total_downtime_hours', models.FloatField()),
                ('uptime_percentage', models.FloatField()),
                ('scheduled_maintenance_hours', models.FloatField()),
                ('unscheduled_outage_hours', models.FloatField()),
                ('critical_systems_affected', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('system_comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUptimeLive',
            fields=[
                ('total_downtime_hours', models.FloatField()),
                ('uptime_percentage', models.FloatField()),
                ('scheduled_maintenance_hours', models.FloatField()),
                ('unscheduled_outage_hours', models.FloatField()),
                ('critical_systems_affected', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('system_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUptimeTemp',
            fields=[
                ('total_downtime_hours', models.FloatField()),
                ('uptime_percentage', models.FloatField()),
                ('scheduled_maintenance_hours', models.FloatField()),
                ('unscheduled_outage_hours', models.FloatField()),
                ('critical_systems_affected', models.PositiveIntegerField()),
                ('reported_date', models.DateField(default='now,')),
                ('system_comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
