# Generated by Django 5.0 on 2024-11-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmanagementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetManagementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmanagementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssetManagementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticsandfleetmanagementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LogisticsAndFleetManagementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logisticsandfleetmanagementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LogisticsAndFleetManagementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeexpenseaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfficeExpenseAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeexpenseaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfficeExpenseAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
