# Generated by Django 5.0 on 2024-11-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchperformanceaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BranchPerformanceAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchperformanceaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BranchPerformanceAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientoutreachaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientOutreachAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientoutreachaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientOutreachAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandisbursementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LoanDisbursementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandisbursementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LoanDisbursementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioqualityaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PortfolioQualityAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioqualityaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PortfolioQualityAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
