# Generated by Django 5.0 on 2024-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
                ('equity', models.FloatField()),
                ('asset_breakdown', models.TextField()),
                ('liability_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
                ('equity', models.FloatField()),
                ('asset_breakdown', models.TextField()),
                ('liability_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetLive',
            fields=[
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
                ('equity', models.FloatField()),
                ('asset_breakdown', models.TextField()),
                ('liability_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetTemp',
            fields=[
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
                ('equity', models.FloatField()),
                ('asset_breakdown', models.TextField()),
                ('liability_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatementAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('inflows', models.FloatField()),
                ('outflows', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('inflow_sources', models.TextField()),
                ('outflow_categories', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatementHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('inflows', models.FloatField()),
                ('outflows', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('inflow_sources', models.TextField()),
                ('outflow_categories', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatementLive',
            fields=[
                ('inflows', models.FloatField()),
                ('outflows', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('inflow_sources', models.TextField()),
                ('outflow_categories', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatementTemp',
            fields=[
                ('inflows', models.FloatField()),
                ('outflows', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('inflow_sources', models.TextField()),
                ('outflow_categories', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatementAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('revenue', models.FloatField()),
                ('operating_expenses', models.FloatField()),
                ('net_income', models.FloatField()),
                ('revenue_sources', models.TextField()),
                ('expense_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatementHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('revenue', models.FloatField()),
                ('operating_expenses', models.FloatField()),
                ('net_income', models.FloatField()),
                ('revenue_sources', models.TextField()),
                ('expense_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatementLive',
            fields=[
                ('revenue', models.FloatField()),
                ('operating_expenses', models.FloatField()),
                ('net_income', models.FloatField()),
                ('revenue_sources', models.TextField()),
                ('expense_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatementTemp',
            fields=[
                ('revenue', models.FloatField()),
                ('operating_expenses', models.FloatField()),
                ('net_income', models.FloatField()),
                ('revenue_sources', models.TextField()),
                ('expense_breakdown', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanLossProvisionAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('loans_at_risk', models.FloatField()),
                ('provision_rate', models.FloatField()),
                ('required_provisions', models.FloatField()),
                ('loan_categories', models.TextField()),
                ('remarks', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanLossProvisionHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('loans_at_risk', models.FloatField()),
                ('provision_rate', models.FloatField()),
                ('required_provisions', models.FloatField()),
                ('loan_categories', models.TextField()),
                ('remarks', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanLossProvisionLive',
            fields=[
                ('loans_at_risk', models.FloatField()),
                ('provision_rate', models.FloatField()),
                ('required_provisions', models.FloatField()),
                ('loan_categories', models.TextField()),
                ('remarks', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanLossProvisionTemp',
            fields=[
                ('loans_at_risk', models.FloatField()),
                ('provision_rate', models.FloatField()),
                ('required_provisions', models.FloatField()),
                ('loan_categories', models.TextField()),
                ('remarks', models.TextField()),
                ('reported_date', models.DateField(default='now,')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
