# Generated by Django 5.0 on 2024-11-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BalanceSheetAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancesheetaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BalanceSheetAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowstatementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CashFlowStatementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflowstatementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CashFlowStatementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomestatementaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncomeStatementAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomestatementaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncomeStatementAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanlossprovisionaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LoanLossProvisionAudit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanlossprovisionaudit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LoanLossProvisionAudit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
