# Generated by Django 5.0 on 2024-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivableAgingAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('current', models.FloatField()),
                ('overdue_30_days', models.FloatField()),
                ('overdue_60_days', models.FloatField()),
                ('overdue_90_days', models.FloatField()),
                ('overdue_90_days_plus', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('total_receivables', models.FloatField()),
                ('comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivableAgingHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('current', models.FloatField()),
                ('overdue_30_days', models.FloatField()),
                ('overdue_60_days', models.FloatField()),
                ('overdue_90_days', models.FloatField()),
                ('overdue_90_days_plus', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('total_receivables', models.FloatField()),
                ('comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivableAgingLive',
            fields=[
                ('current', models.FloatField()),
                ('overdue_30_days', models.FloatField()),
                ('overdue_60_days', models.FloatField()),
                ('overdue_90_days', models.FloatField()),
                ('overdue_90_days_plus', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('total_receivables', models.FloatField()),
                ('comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivableAgingTemp',
            fields=[
                ('current', models.FloatField()),
                ('overdue_30_days', models.FloatField()),
                ('overdue_60_days', models.FloatField()),
                ('overdue_90_days', models.FloatField()),
                ('overdue_90_days_plus', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('total_receivables', models.FloatField()),
                ('comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAgingAudit',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('overdue_0_30_days', models.FloatField()),
                ('overdue_31_60_days', models.FloatField()),
                ('overdue_61_90_days', models.FloatField()),
                ('overdue_91_days_plus', models.FloatField()),
                ('total_outstanding_loans', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('in_temp', 'In Temp')], default='in_temp', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAgingHistory',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('overdue_0_30_days', models.FloatField()),
                ('overdue_31_60_days', models.FloatField()),
                ('overdue_61_90_days', models.FloatField()),
                ('overdue_91_days_plus', models.FloatField()),
                ('total_outstanding_loans', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('comments', models.TextField()),
                ('custom_record_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAgingLive',
            fields=[
                ('overdue_0_30_days', models.FloatField()),
                ('overdue_31_60_days', models.FloatField()),
                ('overdue_61_90_days', models.FloatField()),
                ('overdue_91_days_plus', models.FloatField()),
                ('total_outstanding_loans', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_deactivate', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAgingTemp',
            fields=[
                ('overdue_0_30_days', models.FloatField()),
                ('overdue_31_60_days', models.FloatField()),
                ('overdue_61_90_days', models.FloatField()),
                ('overdue_91_days_plus', models.FloatField()),
                ('total_outstanding_loans', models.FloatField()),
                ('reported_date', models.DateField(default='now,')),
                ('comments', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unauthorized', 'Un Authorized'), ('unauthorized_sent', 'Un Authorized Send'), ('unauthorized_return', 'Un Authorized Return')], default='unauthorized', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
